/**
 * The dungeon director.
 *
 * Two steps, and the order between them is the whole architecture:
 *
 *   1. **`generateRunPlan`** decides the *shape of the run* — ten dramatic
 *      moments and the ways between them — and names no room at all.
 *   2. **`materializeRunPlan`** fills each moment with an authored place, by
 *      asking `resolveRoom`, and connects them into a `RunMap`.
 *
 * The director is not the creative party here. The creative work is the room
 * library; this file's whole responsibility is *choose the right authored place
 * for the right dramatic moment, connect those places into a coherent descent,
 * and never put content into art that cannot support it.*
 *
 * ## It runs once
 *
 * A map is generated by `START_RUN` and stored in `RunState`. Nothing
 * regenerates it — not a render, not a navigation, not a reload, not CONTINUE,
 * not a fixture. The seed is what makes generation reproducible; **the saved
 * map is what makes the run true**, and after generation it is the only
 * authority. That is the same law the reducer already keeps for a ritual's
 * roll and a chest's relic: record the result, never recompute the event.
 */

import { resolveEncounter, resolveRoom } from '../content/roomResolver.js'
import type { RoomRequest } from '../content/roomResolver.js'
import { DESCENT, way } from '../content/runPlans.js'
import type { PlanEdge, RoomSlot, RunPlan } from '../content/runPlans.js'
import type { Territory } from '../content/roomTypes.js'
import { Rng } from './rng.js'
import { validateRun } from './mapValidation.js'
import type { MapExit, RunMap, RunRoom } from './map.js'

/**
 * Where the map's draws sit, clear of every other stream in the run.
 *
 * The run's generator is positioned by history everywhere else — see
 * `rngFor` in `reducer.ts` — but generation happens before there is any
 * history, so it gets a constant of its own instead.
 */
const MAP_SALT = 0x5b2d_0f11

/**
 * The shape of a run.
 *
 * One authored grammar today, and the seed is not yet consulted: the first
 * director's job is to reproduce the descent the slice already had, so that
 * the architecture is what changed and the game is not. The parameter is here
 * because the *next* thing this function does is choose among grammars, and a
 * signature that had to change for that would mean every caller did too.
 */
export function generateRunPlan(_seed: number): RunPlan {
  return DESCENT
}

/** How many rooms back the resolver tries not to repeat itself. */
const RECENT = 2

/**
 * The plan, filled with authored places.
 *
 * Slots are visited in plan order, so the same seed walks the same sequence of
 * draws and lands on the same rooms. Every ordering decision below is
 * load-bearing for that: change the traversal and the same seed becomes a
 * different run.
 */
export function materializeRunPlan(plan: RunPlan, seed: number): RunMap {
  const rng = new Rng((seed ^ MAP_SALT) >>> 0)

  const outgoing = (id: string): readonly PlanEdge[] => plan.edges.filter((e) => e.from === id)
  const incoming = (id: string): readonly PlanEdge[] => plan.edges.filter((e) => e.to === id)

  const nodes: Record<string, RunRoom> = {}
  const recent: string[] = []

  for (const slot of plan.nodes) {
    const ways = outgoing(slot.id)
    const request = requestFor(slot, incoming(slot.id).length, ways.length, recent)
    const chosen = resolveRoom(request, rng)
    const enemyId = resolveEncounter(chosen, slot, rng)

    // The ways out, in the plan's order. First out of a junction is the primary
    // bed on the tray, which is why the plan states the stair before the deep.
    const exits: MapExit[] = ways.map((edge) => {
      const copy = way(edge.way)
      return { label: copy.label, to: edge.to, sense: copy.sense }
    })

    nodes[slot.id] = {
      id: slot.id,
      templateId: chosen.id,
      role: chosen.role,
      territory: chosen.territory,
      depth: slot.depth,
      exits,
      ...(enemyId ? { enemyId } : {}),
    }

    recent.unshift(chosen.id)
    recent.length = Math.min(recent.length, RECENT)
  }

  const start = plan.nodes.find((s) => incoming(s.id).length === 0)
  if (!start) throw new Error('the plan has no room with nothing leading into it')

  return {
    start: start.id,
    nodes,
    territorySequence: sequenceOf(plan, nodes),
  }
}

/**
 * What the descent looks like from a long way back.
 *
 * The territories in depth order with consecutive repeats collapsed, so a run
 * through four ossuary rooms reads as one stretch of bone country rather than
 * four. Nothing gameplay-facing consumes it yet; it is here because it is the
 * one fact about a run that a later plan will want to *choose*, and deriving it
 * after the fact would mean deriving it in two places.
 */
function sequenceOf(plan: RunPlan, nodes: Readonly<Record<string, RunRoom>>): readonly Territory[] {
  const out: Territory[] = []
  for (const slot of [...plan.nodes].sort((a, b) => a.depth - b.depth)) {
    const territory = nodes[slot.id]?.territory
    if (territory && out[out.length - 1] !== territory) out.push(territory)
  }
  return out
}

function requestFor(
  slot: RoomSlot,
  entrances: number,
  exits: number,
  recent: readonly string[],
): RoomRequest {
  if (!slot.territory) throw new Error(`slot ${slot.id} does not say where it is`)
  return {
    role: slot.role,
    territory: slot.territory,
    depth: slot.depth,
    entrances,
    exits,
    ...(slot.requiredTags ? { requiredTags: slot.requiredTags } : {}),
    ...(slot.forbiddenTags ? { forbiddenTags: slot.forbiddenTags } : {}),
    recentTemplates: recent,
  }
}

/**
 * A whole run's map, from a seed.
 *
 * Validated before it is returned, and loudly: a descent that fails the grammar
 * is a content or director bug, and the place to find out is the press of START
 * rather than a GO button four rooms down that leads nowhere.
 */
export function generateRun(seed: number): RunMap {
  const map = materializeRunPlan(generateRunPlan(seed), seed)
  const problems = validateRun(map)
  if (problems.length > 0) {
    throw new Error(`this run is not a run:\n${problems.map((p) => `  [${p.code}] ${p.message}`).join('\n')}`)
  }
  return map
}
