/**
 * The dungeon director.
 *
 * Two steps, and the order between them is the whole architecture:
 *
 *   1. **`generateRunPlan`** decides the *shape of the run* — ten dramatic
 *      moments and the ways between them — and names no room at all.
 *   2. **`materializeRunPlan`** fills each moment with an authored place, by
 *      asking `resolveRoom`, and connects them into a `RunMap`.
 *
 * The director is not the creative party here. The creative work is the room
 * library; this file's whole responsibility is *choose the right authored place
 * for the right dramatic moment, connect those places into a coherent descent,
 * and never put content into art that cannot support it.*
 *
 * ## It runs once
 *
 * A map is generated by `START_RUN` and stored in `RunState`. Nothing
 * regenerates it — not a render, not a navigation, not a reload, not CONTINUE,
 * not a fixture. The seed is what makes generation reproducible; **the saved
 * map is what makes the run true**, and after generation it is the only
 * authority. That is the same law the reducer already keeps for a ritual's
 * roll and a chest's relic: record the result, never recompute the event.
 */

import { BARGAIN_POOL, CARVER_POOL, DIE_PRICE, TREASURE_DIE } from '../content/dice.js'
import type { CoreDieId } from '../content/dice.js'
import { resolveEncounter, resolveRoom } from '../content/roomResolver.js'
import type { RoomRequest } from '../content/roomResolver.js'
import { GRAMMARS, way } from '../content/runPlans.js'
import type { PlacementId, PlanEdge, RoomSlot, RunPlan } from '../content/runPlans.js'
import type { RoomTemplate, Territory } from '../content/roomTypes.js'
import { HINT_CARVING } from '../content/text.js'
import { Rng } from './rng.js'
import { validateRun } from './mapValidation.js'
import type { DieOffer, MapExit, RunMap, RunRoom } from './map.js'

/**
 * Where the map's draws sit, clear of every other stream in the run.
 *
 * The run's generator is positioned by history everywhere else — see
 * `rngFor` in `reducer.ts` — but generation happens before there is any
 * history, so it gets a constant of its own instead.
 */
const MAP_SALT = 0x5b2d_0f11

/**
 * Where the choice of grammar sits, clear of every room draw.
 *
 * A salt of its own, so that adding a fourth grammar — or changing how the
 * treasure is chosen — cannot perturb which rooms a seed lands on.
 */
const GRAMMAR_SALT = 0x2f91_77c3

/**
 * The shape of a run.
 *
 * **Three grammars, and the seed chooses.** The parameter was put here by the
 * first director against exactly this day: a run is no longer one shape with two
 * branches in it, it is one of three descents that agree on almost nothing
 * except that the keeper and the way out are in the threshold.
 *
 * Drawn off a salt of its own rather than off the map's generator, so that the
 * grammar choice and the room draws cannot move each other.
 */
export function generateRunPlan(seed: number): RunPlan {
  const rng = new Rng(((seed >>> 0) ^ GRAMMAR_SALT) >>> 0)
  return GRAMMARS[rng.int(GRAMMARS.length)]!
}

/** How many rooms back the resolver tries not to repeat itself. */
const RECENT = 2

/**
 * Draw `count` distinct dice out of a pool, without replacement.
 *
 * Seeded, never shuffled, and without replacement inside one room: the Carver
 * never has the same die twice on one table, because two of a thing at one price
 * is not a choice. A pool shorter than `count` simply offers fewer, which is the
 * same answer `drawWeighted` gives a reward pool that runs dry.
 */
function drawDice(pool: readonly CoreDieId[], count: number, rng: Rng): readonly CoreDieId[] {
  const left = [...pool]
  const out: CoreDieId[] = []
  while (out.length < count && left.length > 0) out.push(left.splice(rng.int(left.length), 1)[0]!)
  return out
}

/**
 * Everything standing in one room, seated.
 *
 * Two sources and one seating rule. The room's own `exchange` is a fact about the
 * place — the Bone Carver has two dice on the altar because that is what it is —
 * and the plan's `placements` are the director's. Both take **spare seats**, in
 * that order, and a `hint-carving` takes none because it is prose.
 *
 * Nothing here invents a position. If a room was asked to hold more than its
 * picture has seats for, the extras are dropped and `validateRunMap` fails the
 * run by name — a seat the view had to make up would be a press on a wall.
 */
function seatThings(
  chosen: RoomTemplate,
  placements: readonly PlacementId[],
  rng: Rng,
): { readonly dice: readonly DieOffer[]; readonly carvings: readonly string[] } {
  const seats = chosen.spareSeats ?? []
  const wanted: { readonly die: CoreDieId; readonly price?: number; readonly kind: DieOffer['kind'] }[] = []
  const carvings: string[] = []

  // What the room sells, first, so the Carver's own table is seated before
  // anything a plan stands beside it.
  if (chosen.exchange) {
    for (const die of drawDice(CARVER_POOL, chosen.exchange.count, rng)) {
      wanted.push({ die, price: chosen.exchange.price, kind: 'carver' })
    }
  }

  for (const placement of placements) {
    switch (placement) {
      case 'bargain-die':
        // One specific die, chained, priced. **Never generic power** — there is
        // no shape of placement that could express it.
        wanted.push({ die: drawDice(BARGAIN_POOL, 1, rng)[0] ?? 'bone', price: DIE_PRICE, kind: 'bargain' })
        break
      case 'treasure':
        // Unpriced, and the one die that is never in either pool. Its price is
        // the road to it.
        wanted.push({ die: TREASURE_DIE, kind: 'treasure' })
        break
      case 'hint-carving':
        carvings.push(HINT_CARVING)
        break
    }
  }

  const dice: DieOffer[] = []
  wanted.forEach((thing, index) => {
    const seat = seats[index]
    if (!seat) return
    dice.push({ ...thing, seat: seat.id, at: seat.at })
  })
  return { dice, carvings }
}

/**
 * The plan, filled with authored places.
 *
 * Slots are visited in plan order, so the same seed walks the same sequence of
 * draws and lands on the same rooms. Every ordering decision below is
 * load-bearing for that: change the traversal and the same seed becomes a
 * different run.
 */
export function materializeRunPlan(plan: RunPlan, seed: number): RunMap {
  const rng = new Rng((seed ^ MAP_SALT) >>> 0)

  const outgoing = (id: string): readonly PlanEdge[] => plan.edges.filter((e) => e.from === id)
  const incoming = (id: string): readonly PlanEdge[] => plan.edges.filter((e) => e.to === id)

  const nodes: Record<string, RunRoom> = {}
  const recent: string[] = []

  // **Which of the two candidates is the treasure, for this seed.** Drawn first,
  // before any room, so the answer is a property of the descent rather than of
  // how many dice happened to be drawn on the way to it. The loser keeps the
  // ordinary chained bargain it declared — so one mouth of that fork holds the
  // Hand and the other holds a die, and nothing on screen says which.
  const treasure = plan.treasureCandidates[rng.int(plan.treasureCandidates.length)]!

  for (const slot of plan.nodes) {
    const ways = outgoing(slot.id)
    const request = requestFor(slot, incoming(slot.id).length, ways.length, recent)
    const chosen = resolveRoom(request, rng)
    const enemyId = resolveEncounter(chosen, slot, rng)
    const placements = (slot.placements ?? []).map((p) =>
      slot.id === treasure && p === 'bargain-die' ? ('treasure' as PlacementId) : p,
    )
    const { dice, carvings } = seatThings(chosen, placements, rng)

    // The ways out, in the plan's order, each bound to the anchor at the same
    // position in the room's picture. First out of a junction is the primary
    // one, which is why the plan states the stair before the deep — and it is
    // now also *where* the first way stands, because the anchors are declared
    // in the same order for the same reason.
    const exits: MapExit[] = ways.map((edge, index) => {
      const copy = way(edge.way)
      const anchor = chosen.exitAnchors?.[index]
      return {
        label: copy.label,
        to: edge.to,
        sense: copy.sense,
        kind: edge.kind,
        ...(anchor ? { at: anchor.at } : {}),
      }
    })

    nodes[slot.id] = {
      id: slot.id,
      templateId: chosen.id,
      role: chosen.role,
      // What the **slot** asked for, not the template's first territory: a
      // picture that honestly reads in two stretches of the descent is standing
      // in the one this moment is in. `territoriesOf` is what holds the two
      // together, in `mapValidation.ts`.
      territory: slot.territory ?? chosen.territory,
      depth: slot.depth,
      exits,
      ...(enemyId ? { enemyId } : {}),
      ...(dice.length > 0 ? { dice } : {}),
      ...(carvings.length > 0 ? { carvings } : {}),
    }

    recent.unshift(chosen.id)
    recent.length = Math.min(recent.length, RECENT)
  }

  const start = plan.nodes.find((s) => incoming(s.id).length === 0)
  if (!start) throw new Error('the plan has no room with nothing leading into it')

  return {
    start: start.id,
    nodes,
    territorySequence: sequenceOf(plan, nodes),
  }
}

/**
 * What the descent looks like from a long way back.
 *
 * The territories in depth order with consecutive repeats collapsed, so a run
 * through four ossuary rooms reads as one stretch of bone country rather than
 * four. Nothing gameplay-facing consumes it yet; it is here because it is the
 * one fact about a run that a later plan will want to *choose*, and deriving it
 * after the fact would mean deriving it in two places.
 */
function sequenceOf(plan: RunPlan, nodes: Readonly<Record<string, RunRoom>>): readonly Territory[] {
  const out: Territory[] = []
  for (const slot of [...plan.nodes].sort((a, b) => a.depth - b.depth)) {
    const territory = nodes[slot.id]?.territory
    if (territory && out[out.length - 1] !== territory) out.push(territory)
  }
  return out
}

function requestFor(
  slot: RoomSlot,
  entrances: number,
  exits: number,
  recent: readonly string[],
): RoomRequest {
  if (!slot.territory) throw new Error(`slot ${slot.id} does not say where it is`)
  return {
    role: slot.role,
    territory: slot.territory,
    depth: slot.depth,
    entrances,
    exits,
    ...(slot.requiredTags ? { requiredTags: slot.requiredTags } : {}),
    ...(slot.forbiddenTags ? { forbiddenTags: slot.forbiddenTags } : {}),
    recentTemplates: recent,
  }
}

/**
 * A whole run's map, from a seed.
 *
 * Validated before it is returned, and loudly: a descent that fails the grammar
 * is a content or director bug, and the place to find out is the press of START
 * rather than a GO button four rooms down that leads nowhere.
 */
export function generateRun(seed: number): RunMap {
  const map = materializeRunPlan(generateRunPlan(seed), seed)
  const problems = validateRun(map)
  if (problems.length > 0) {
    throw new Error(`this run is not a run:\n${problems.map((p) => `  [${p.code}] ${p.message}`).join('\n')}`)
  }
  return map
}
