/**
 * The whole of the game's state, as plain serialisable data.
 *
 * Two scopes and no rituals: `meta` survives a death, `run` does not. Both are
 * ordinary objects. Every transition is a pure function in `reducer.ts`, and
 * nothing outside that file may mutate any of this.
 *
 * `mode` is the journey's state machine. It is explicit because every
 * session-ending bug this reset exists to fix — the death screen you could get
 * stuck on, the choosing screen with no way out, the tab that ate its own
 * press — was a mode the shell had to infer from four other fields.
 *
 * ## The pile is the player
 *
 * A run's life is `run.bones`, and there is no second life field: no `hp`, no
 * `maxHp`, no shield, no armour. A hit removes bones from the pile. **Bones
 * are health and only health** — the hand is six dice from the first fight to
 * the last turn of the boss, and nothing reads the pile to decide how many are
 * in the air. Enemies *do* carry an explicit `enemyHp`, deliberately — see
 * `docs/COMBAT.md`.
 *
 * ## The loadout is ids, not objects
 *
 * `run.hand`, `run.ironDice`, `run.itemDice` and `run.talismans` hold content
 * ids. A save carries which things a run is carrying and never a copy of what
 * they do, for the same reason `run.roomId` is a node id rather than a room: a
 * table changed in `content/dice.ts` must not be able to disagree with a save
 * written before it.
 */

import type { ScoreId, NamedHandId } from '../combat/hands.js'
import type { IronRoll, ItemRoll } from '../combat/loadout.js'
import type { DieValue } from '../combat/roll.js'
import type { CoreDieId, IronDieId, ItemDieId, TalismanId } from '../content/dice.js'
import type { RewardId } from '../content/rewards.js'
import type { KeyId } from '../content/areas.js'
import type { RunMap } from './map.js'

/**
 * Bumped whenever the shape below changes. Old saves are not migrated.
 *
 * **9.** The Yahtzee reset changed the run's life from a two-part pile to one
 * number and replaced the whole of `CombatState`.
 *
 * **10.** The loadout wave. `RunState` gained `hand`, `ironDice`, `itemDice`
 * and `talismans`; `CombatState` gained the turn's settled iron; and
 * `AttackRecord` gained every beat of the cascade. A save written by 9 has
 * neither the six slots nor an iron die, and a fight resumed out of one would
 * be a fight with no terrain. There is no migration ladder and there is not
 * going to be one: an old save is detected, discarded, and reported.
 *
 * **11.** The reel wave, and **one bump for the whole of it**: a fresh run
 * starts with an empty loadout, what a fight pays is `run.loot` on the node
 * rather than an `offer` on a screen, the `reward` mode is gone, a map's exits
 * carry the kind of edge they were, and the descent forked. A save from 10
 * would resume into a mode that no longer exists holding an offer nothing can
 * read. Discarded, and reported.
 *
 * **12.** The crooked bones wave, and **one bump for the whole of it**: there
 * are eight core dice rather than one, a `RunRoom` can hold priced dice and cut
 * prose, `RunState` records which of those dice have been claimed, three
 * grammars generate three differently shaped maps, and the enemies' damage is a
 * ladder rather than a number. A save from 11 holds a map with no seats in it,
 * generated by a director that knew one grammar, and a hand of six dice that
 * could only ever have been bones. There is no migration ladder and there is not
 * going to be one: an old save is detected, discarded, and reported.
 */
// 13: cyclic spatial maps, progression keys, and independently spent fonts.
export const SAVE_VERSION = 13

/**
 * The screens.
 *
 * `reward` is **gone**, and it is not coming back under another name. What a
 * fight pays now falls in the room and is picked up in the room — discover,
 * reveal, inspect, decide, take, possess, all in the world — so there is no
 * mode for *what do I take*, because there is no screen for it. See
 * `docs/COMBAT.md` § Loot.
 */
export type Mode = 'title' | 'explore' | 'combat' | 'dead' | 'complete'

/**
 * One settled exchange, in full.
 *
 * Written by SCORE before a frame of it is shown, and read by the presentation
 * in order. Every number the sequence says out loud is on here: the animation
 * reveals an outcome the reducer already computed, and it recomputes nothing.
 *
 * It is written out beat by beat because the cascade is played beat by beat —
 * the readout resolves `sum × multiplier` before the item dice fire, and the
 * item dice fire before the blow lands. A presentation that had only the final
 * damage would have to invent the middle of that, which is exactly the thing
 * this codebase does not let a presentation do.
 */
export interface AttackRecord {
  /** The faces that were on the table when the hand was scored. */
  readonly dice: readonly DieValue[]
  readonly hand: ScoreId
  readonly sum: number
  readonly multiplier: number
  /** `floor(sum × multiplier)` — the line alone, before anything flat. */
  readonly base: number

  /** What the item dice rolled, in loadout order. Empty when none are carried. */
  readonly itemRolls: readonly ItemRoll[]
  /** What they added to the total. */
  readonly itemFlats: number
  /** What they charged, in bones, at the item beat. */
  readonly itemCost: number
  /** Talismans whose line matched, and what they added. Flat, always. */
  readonly talismansFired: readonly TalismanId[]
  readonly talismanFlat: number

  /** `max(1, base + itemFlats + talismanFlat)`. Zero when the blow never landed. */
  readonly damage: number
  /**
   * Whether the blow landed at all.
   *
   * False in exactly one case: an item die's cost face emptied the pile at the
   * item beat, which is *before* the blow. A cost is a cost — the run ends
   * there and the enemy is untouched. See `docs/COMBAT.md` § Costs.
   */
  readonly landed: boolean

  readonly enemyHpBefore: number
  readonly enemyHpAfter: number

  /** The enemy's own fixed number, before the iron stood in front of it. */
  readonly enemyHit: number
  /** What the iron die held off it this turn. */
  readonly block: number
  /** `max(0, enemyHit − block)`. Zero when the attack finished it. */
  readonly retaliation: number
  readonly bonesBefore: number
  readonly bonesAfter: number
}

/**
 * A fight in progress.
 *
 * Small, serialisable, and with no phase enum: the position is derivable and
 * saying it twice is how two fields come to disagree.
 *
 *   `dice.length === 0`                 waiting for the initial ROLL
 *   `dice.length > 0 && rollsUsed < 3`  may SCORE or REROLL
 *   `dice.length > 0 && rollsUsed === 3` must SCORE
 *
 * What is *not* here is as deliberate: no held flags, because a hold is a
 * thought the view is editing and a reload may forget it; no enemy dice,
 * because the enemy rolls nothing; and no clock anywhere, because a frame is
 * not a fact about a run.
 */
export interface CombatState {
  readonly enemyId: string
  /** 1-based attack round. Round 1 is the fight opening. */
  readonly round: number

  readonly enemyHp: number
  readonly enemyMaxHp: number

  /** Named categories deliberately scored during this fight. CRAP is never here. */
  readonly usedHands: readonly NamedHandId[]

  /** The current attack's core dice. Empty before the initial roll of a round. */
  readonly dice: readonly DieValue[]
  /** 0 before rolling, then 1..3. */
  readonly rollsUsed: 0 | 1 | 2 | 3

  /**
   * The iron, settled for this turn.
   *
   * Thrown by ROLL, in the same tick, alongside the six — and never again: a
   * REROLL leaves it exactly where it is, because what it shows is the turn's
   * terrain rather than part of the dice game. Empty before the initial roll,
   * and empty for a run that carries no iron.
   *
   * It is here rather than derived because it is a *draw*: recorded once, the
   * way a ritual's roll is, so a reload reads it instead of throwing it again.
   */
  readonly ironRolls: readonly IronRoll[]

  /** The last settled exchange, for the copy and the beats. */
  readonly lastAttack?: AttackRecord
  /**
   * It is dead, and the fight is being held open on the picture of that.
   *
   * A flag, not a clock. There is no frame index and no start time here,
   * because a frame is not a fact about the run: the sequence in `app/app.ts`
   * owns which picture is up, `content/defeat.ts` owns how long each one is,
   * and a reload lands on this flag and plays out from the settled frame.
   */
  readonly defeated?: boolean
  /** What just happened, for the word band and the beats. */
  readonly log: readonly string[]
}

/** What a die in a font can land on. */
export type RitualRoll = 1 | 2 | 3 | 4 | 5 | 6

/**
 * A ritual the run has already resolved.
 *
 * The authoritative record of one press: what it rolled, what that gave back,
 * and how much room there was at the moment it was rolled. It exists so the
 * answer cannot be recomputed — a reload replays no draw, a second press finds
 * the room already answered, and the sequence on screen is reading this rather
 * than deciding anything.
 */
export interface RitualState {
  /** The **node** it was rolled in, so two fonts in one run are two fonts. */
  readonly roomId: string
  readonly roll: RitualRoll
  /** Common bones actually put back. Zero is a real answer, at the ceiling. */
  readonly restored: number
  /** How many bones short of the ceiling the pile was, before the press. */
  readonly missingBefore: number
}

/**
 * What a room's objects have been left doing.
 *
 * A ritual is one press and one answer, so `RitualState` records a *result*.
 * These rooms are the other shape: several objects, each with its own settled
 * position, and an order between them that is the puzzle. So this records
 * **where everything is standing**, and nothing else.
 *
 * A discriminated union rather than a bag of optional fields, because the two
 * rooms share no object: a `brazier` on a vault would be a state the game
 * cannot reach, and `templateId` is what stops it being expressible.
 *
 * `templateId` is the one place in the whole of state where a *template* id
 * appears, and it is here because it is answering "what kind of machinery is
 * this", not "which room". Which room is the key these are stored under in
 * `run.rooms`, and that key is a **node** id — so two runs through the same
 * Reliquary template are two chests, two levers and two relics.
 *
 * What is deliberately absent is any clock. No frame index, no elapsed time, no
 * "is animating" — the settled position is the whole truth, every picture is
 * derived from it, and a reload paints the room from this and nothing else.
 * That is the same rule `combat.defeated` is built on.
 */
export type RoomInteractionState =
  | {
      readonly templateId: 'reliquary'
      readonly bellRung: boolean
      readonly brazier: 'lit' | 'out'
      readonly lever: 'up' | 'down'
      readonly chest: 'closed' | 'open'
    }
  | {
      readonly templateId: 'chain-vault'
      readonly chain: 'off' | 'on'
      readonly cage: 'raised' | 'lowered'
      readonly pressurePlate: 'off' | 'on'
      readonly lever: 'up' | 'down'
      readonly gate: 'closed' | 'open'
    }
  | {
      /**
       * The Offertory: the Chain Vault's grammar spent a second way.
       *
       * The candles go out so the carved price can be read, the price is paid
       * on the altar, and the wall recess and the way on open together. The
       * greedy press — prying the recess before paying — is priced exactly as
       * the vault's mis-pull is: it costs a bone, moves nothing, and can be
       * made as many times as there is blood for it.
       */
      readonly templateId: 'offertory'
      readonly candles: 'lit' | 'out'
      readonly paid: boolean
      readonly recess: 'shut' | 'open'
    }

/**
 * One found thing, lying where it was found.
 *
 * The whole of the loot economy, and it is deliberately three fields. There is
 * no screen mode behind it, no offer, no pending choice and no timer: a thing
 * that has been revealed is **in the room**, and the only question left is
 * whether the player walks over and takes it.
 *
 * `taken` is a flag rather than a removal for the same reason `RitualState`
 * records a roll: the draw happened once, in the reducer, and a record that
 * deleted itself would leave nothing to stop a second visit drawing again.
 * Maze backtracking makes this record essential: returning cannot pay twice.
 */
export interface LootItem {
  readonly id: RewardId
  readonly taken: boolean
}

export interface RunState {
  /** Progression keys are retained after use and do not occupy combat slots. */
  readonly keys?: readonly KeyId[]
  /** One recorded result per font, preserved across revisits and reloads. */
  readonly rituals?: Readonly<Record<string, RitualState>>
  readonly seed: number
  /**
   * The descent, settled.
   *
   * Generated once by `START_RUN` and never again — not on a render, a
   * navigation, a reload, a CONTINUE or a fixture. The seed is what makes
   * generation reproducible; this is what makes the run *true*, and after the
   * press of START it is the only authority on where anything leads.
   */
  readonly map: RunMap
  /**
   * Which room of the map. A **node** id, not a template id.
   *
   * Everything below that names a room names one of these, for the reason
   * `game/map.ts` gives at length: a template used twice is two rooms, and
   * every scrap of per-room state has to be able to tell them apart.
   */
  readonly roomId: string

  // ── life ──────────────────────────────────────────────────────────────
  /**
   * The pile. One number, and it is the player's whole life.
   *
   * **Bones are health and only health.** They were once the width of the
   * attack as well; that coupling is repealed, because the run's progression
   * is replacement — a found die takes one of the six slots below — and a
   * width that shrank with the pile would spend the fight taking those slots
   * away again. There is no second life field anywhere and there is not to be
   * one.
   */
  readonly bones: number

  // ── the loadout ───────────────────────────────────────────────────────
  /**
   * The six slots the attack throws. Always six, and never a seventh.
   *
   * A found die **replaces** one of these; the player chooses which. That is
   * the whole of the progression model, and it is why the array has a fixed
   * length rather than a cap: growth here would be growth in the number of
   * dice, which is the thing that was ruled out.
   */
  readonly hand: readonly CoreDieId[]
  /**
   * Armour, and it is a die rather than a stat.
   *
   * It rolls each turn on ROLL and blocks what it shows off that turn's
   * answer. An always-on damage-reduction stat made plate dominate every
   * loadout it appeared in; that was measured, and moving the effect onto a
   * die fixed the dominance without touching the numbers. One, this wave.
   */
  readonly ironDice: readonly IronDieId[]
  /**
   * Upside that fires at Attack, automatically. Two at most, capped in the
   * reducer.
   *
   * **Balance never assumes these.** No gate, target or enemy number may
   * require one.
   */
  readonly itemDice: readonly ItemDieId[]
  /** Flat per-line bonuses. Optional upside, never a gate. */
  readonly talismans: readonly TalismanId[]

  // ── satchel ───────────────────────────────────────────────────────────
  /** The one consumable. */
  readonly vials: number

  /** Which details have been looked at, in the node being stood in. */
  readonly looked: readonly string[]
  /** Nodes whose enemy is already dead. */
  readonly cleared: readonly string[]
  /** Nodes visited, in order. */
  readonly path: readonly string[]
  /** What the last press said. The word band reads this. */
  readonly say: string
  readonly combat?: CombatState
  /** Most recent ritual, retained for its presentation and legacy fixtures. */
  readonly ritual?: RitualState
  /**
   * Where each room's objects have been left, keyed by **node** id.
   *
   * Node, not template — so the same authored room used twice in one descent
   * has two independent chests. `stateOf` is where the two ids meet: the key
   * says which room, and the template says how that kind of room opens.
   *
   * Sparse on purpose: a room that has not been touched has no entry, and its
   * opening position is content rather than something a new run has to write
   * out. `initialRoomState` in `content/interactions.ts` is that opening
   * position, and it is the one place it is stated.
   */
  readonly rooms?: Readonly<Record<string, RoomInteractionState>>
  /**
   * What is lying in each room, keyed by **node** id.
   *
   * Written by whatever revealed it — a fight settling, a chest opening, a
   * price being paid — and never by a screen, because there is no screen. It
   * is sparse: a room that has revealed nothing has no entry.
   */
  readonly loot?: Readonly<Record<string, readonly LootItem[]>>
  /**
   * Which of a room's core dice have been taken off their seats, by **node**.
   *
   * A list of seat positions rather than a copy of the dice, for the same reason
   * `roomId` is a node id: *which* die was on the Carver's left-hand seat is a
   * fact about the descent, settled at the press of START and stored on the map,
   * and a save that carried its own copy could hold a stale one. What a run
   * records is only what it did.
   *
   * Sparse: a room nothing was bought in has no entry. A claimed seat is marked
   * rather than removed — the same ruling `LootItem.taken` is under, and for the
   * same reason: the draw happened once, and returning must never sell it again.
   */
  readonly claimed?: Readonly<Record<string, readonly number[]>>
  /** Why the run ended. */
  readonly cause?: string
}

export interface MetaState {
  readonly runs: number
  readonly wins: number
  /** Everything ever found, so the title screen has something to say. */
  readonly seenRewards: readonly string[]
}

export interface GameState {
  readonly version: number
  readonly mode: Mode
  readonly meta: MetaState
  readonly run?: RunState
  /**
   * Where CONTINUE goes.
   *
   * Boot always lands on the title, so the mode a reload interrupted has to be
   * carried somewhere the title screen is not overwriting. Deriving it instead
   * — *there is combat state, so we were fighting* — is what put the old build
   * back into a fight it had already died in.
   */
  readonly resume?: Mode
}

export const EMPTY_META: MetaState = { runs: 0, wins: 0, seenRewards: [] }

export const TITLE: GameState = { version: SAVE_VERSION, mode: 'title', meta: EMPTY_META }
